# Generated by Django 5.2.8 on 2025-12-17 19:57

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', core.fields.EncryptedTextField(help_text='RUT cifrado')),
                ('rut_hash', models.CharField(db_index=True, editable=False, max_length=64)),
                ('nombre_completo', core.fields.EncryptedTextField()),
                ('direccion', core.fields.EncryptedTextField(blank=True, null=True)),
                ('telefono', core.fields.EncryptedTextField(blank=True, null=True)),
                ('email', core.fields.EncryptedTextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('comuna', models.CharField(max_length=100)),
                ('cesfam', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidad', models.CharField(default='Chilena', max_length=50)),
                ('es_migrante', models.BooleanField(default=False)),
                ('pueblo_originario', models.BooleanField(default=False)),
                ('detalle_pueblo_originario', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_paciente', models.CharField(blank=True, max_length=100, null=True)),
                ('origen_ingreso', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_discapacidad', core.fields.EncryptedTextField(blank=True, null=True)),
                ('observaciones', core.fields.EncryptedTextField(blank=True, null=True)),
                ('vih_positivo', core.fields.EncryptedTextField(default='NO')),
                ('vdrl_reactivo', core.fields.EncryptedTextField(default='NO')),
                ('tiene_plan_parto', models.BooleanField(default=False)),
                ('realizo_visita_guiada', models.BooleanField(default=False)),
                ('tiene_acompanante', models.BooleanField(default=False)),
                ('datos_acompanante', core.fields.EncryptedTextField(blank=True, null=True)),
                ('motivo_sin_acompanante', core.fields.EncryptedTextField(blank=True, null=True)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=10, null=True)),
                ('factor_rh', models.CharField(blank=True, max_length=10, null=True)),
                ('alergias', core.fields.EncryptedTextField(blank=True, null=True)),
                ('antecedentes_medicos', core.fields.EncryptedTextField(blank=True, null=True)),
                ('antecedentes_obstetricos', core.fields.EncryptedTextField(blank=True, null=True)),
                ('gestas', models.IntegerField(default=0)),
                ('partos_vaginales', models.IntegerField(default=0)),
                ('abortos', models.IntegerField(default=0)),
                ('cesareas', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=50)),
                ('tipo_accion', models.CharField(max_length=20)),
                ('modulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_parto', models.CharField(max_length=50)),
                ('edad_gestacional', models.IntegerField()),
                ('profesional_acargo', models.CharField(max_length=150)),
                ('observaciones', core.fields.EncryptedTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='clinical.madre')),
            ],
        ),
        migrations.CreateModel(
            name='AltaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('tipo', models.CharField(default='MEDICA', max_length=50)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='clinical.madre')),
                ('parto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='clinical.parto')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('TI', 'TI'), ('ADMISION', 'Admisión'), ('MATRONA', 'Matrona'), ('ENFERMERA', 'Enfermera'), ('MEDICO', 'Médico'), ('TECNICO', 'Técnico'), ('SUPERVISOR', 'Supervisor')], default='ENFERMERA', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', core.fields.EncryptedTextField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=20)),
                ('peso_gramos', models.IntegerField()),
                ('talla_cm', models.FloatField()),
                ('circunferencia_craneal', models.FloatField(blank=True, null=True)),
                ('apgar_1', models.IntegerField()),
                ('apgar_5', models.IntegerField()),
                ('vacuna_bcg', models.BooleanField(default=False)),
                ('vacuna_hepatitis_b', models.BooleanField(default=False)),
                ('screening_auditivo', models.BooleanField(default=False)),
                ('profilaxis_ocular', models.BooleanField(default=False)),
                ('malformacion_congenita', core.fields.EncryptedTextField(default='NO')),
                ('observaciones', core.fields.EncryptedTextField(blank=True, null=True)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='clinical.parto')),
            ],
        ),
    ]
