# Generated by Django 5.2.8 on 2025-12-08 02:13

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', core.fields.EncryptedTextField(help_text='RUT cifrado (lectura)')),
                ('rut_hash', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('nombre_completo', core.fields.EncryptedTextField(help_text='Nombre completo cifrado')),
                ('direccion', core.fields.EncryptedTextField(blank=True, null=True)),
                ('telefono', core.fields.EncryptedTextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('comuna', models.CharField(max_length=100)),
                ('cesfam', models.CharField(blank=True, max_length=100, null=True)),
                ('nacionalidad', models.CharField(default='Chilena', max_length=50)),
                ('es_migrante', models.BooleanField(default=False)),
                ('pueblo_originario', models.BooleanField(default=False)),
                ('vih_positivo', core.fields.EncryptedTextField(default='NO')),
                ('vdrl_reactivo', core.fields.EncryptedTextField(default='NO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_parto', models.CharField(choices=[('EUTOCICO', 'Eutócico'), ('CESAREA URGENCIA', 'Cesárea Urgencia'), ('CESAREA ELECTIVA', 'Cesárea Electiva'), ('FORCEPS', 'Fórceps'), ('VACUUM', 'Vacuum')], max_length=50)),
                ('edad_gestacional', models.IntegerField(help_text='Semanas de gestación (Columna E)')),
                ('profesional_acargo', models.CharField(max_length=150)),
                ('observaciones', core.fields.EncryptedTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='clinical.madre')),
            ],
        ),
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', core.fields.EncryptedTextField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino'), ('INDETERMINADO', 'Indeterminado')], max_length=20)),
                ('peso_gramos', models.IntegerField()),
                ('talla_cm', models.FloatField()),
                ('circunferencia_craneal', models.FloatField(blank=True, null=True, verbose_name='CC')),
                ('apgar_1', models.IntegerField(verbose_name="Apgar 1'")),
                ('apgar_5', models.IntegerField(verbose_name="Apgar 5'")),
                ('vacuna_bcg', models.BooleanField(default=False)),
                ('vacuna_hepatitis_b', models.BooleanField(default=False)),
                ('screening_auditivo', models.BooleanField(default=False)),
                ('profilaxis_ocular', models.BooleanField(default=False)),
                ('malformacion_congenita', core.fields.EncryptedTextField(default='NO')),
                ('observaciones', core.fields.EncryptedTextField(blank=True, null=True)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='clinical.parto')),
            ],
        ),
    ]
