# Generated by Django 5.2.8 on 2025-12-16 16:00

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='madre',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='datos_acompanante',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='detalle_pueblo_originario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='email',
            field=core.fields.EncryptedTextField(blank=True, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='madre',
            name='motivo_sin_acompanante',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='origen_ingreso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='realizo_visita_guiada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='madre',
            name='tiene_acompanante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='madre',
            name='tiene_plan_parto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='madre',
            name='tipo_discapacidad',
            field=core.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='madre',
            name='tipo_paciente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
