# Generated by Django 5.2.8 on 2025-12-17 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('accion', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('detalles', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='logactividad',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='parto',
            name='hora',
        ),
        migrations.AlterField(
            model_name='madre',
            name='alergias',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='antecedentes_medicos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='antecedentes_obstetricos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='datos_acompanante',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='email',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='motivo_sin_acompanante',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='nombre_completo',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='madre',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='rut',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='rut_hash',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='telefono',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='tipo_discapacidad',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='madre',
            name='vdrl_reactivo',
            field=models.CharField(default='NO', max_length=500),
        ),
        migrations.AlterField(
            model_name='madre',
            name='vih_positivo',
            field=models.CharField(default='NO', max_length=500),
        ),
        migrations.AlterField(
            model_name='parto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='profesional_acargo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='malformacion_congenita',
            field=models.CharField(default='NO', max_length=500),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Alta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='MEDICA', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas', to='clinical.parto')),
            ],
        ),
        migrations.DeleteModel(
            name='AltaMedica',
        ),
        migrations.DeleteModel(
            name='LogActividad',
        ),
    ]
