# Generated by Django 5.2.8 on 2025-12-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_fix_rut_hash'),
        ('clinical', '0002_madre_ciudad_madre_datos_acompanante_and_more'),
    ]

    operations = [
    ]
