# Generated by Django 5.2.8 on 2025-12-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_logaudit_remove_logactividad_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaudit',
            name='rol',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='logaudit',
            name='usuario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
