# Generated by Django 5.2.8 on 2025-12-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_merge_20251216_1312'),
    ]

    operations = [
    ]
