# Generated by Django 5.2.8 on 2025-12-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_fix_rut_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madre',
            name='rut_hash',
            field=models.CharField(db_index=True, default='', editable=False, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
